### ISSUE TITLE
Request that Zoomr be undeleted

### ISSUE THREAD

**Issue by Hypocee** [Noitidart/Zoomr#17]
I request that Zoomr be un-obliterated from the Internet, ideally with its history. Ceasing maintenance and deprecating Zoomr for a clean sheet is completely reasonable, but deprecating and deleting are different things. Instead of making a new repo or a commit that removed all files while keeping the old code history, you've overwritten it here and killed the Mozilla addon page. 
1. Some people are unwilling or unable to update to a version of Firefox that supports Smart Zoom. There's now no way for them to get any of the versions of the extension that they could use before.
2. Smart Zoom is not yet at feature parity with Zoomr.
3. Zoomr was presumably open source for a reason. Now nobody can learn from it.

**Comment by Noitidart** [comment]
Will do this week for sure :)

**Comment by Noitidart** [comment]
I brought the listing back. I need to send another udpate to remove the annoying pop up. I'll make that pop up be unobtrusive (meaning so it wont need your interaction to disappear).

**Comment by Noitidart** [comment]
v1.3 with alert softened released - thanks for being a user of zoomr! Please try it out, if any issues let me know. If it is all good please close this bug :)

**Comment by Hypocee** [comment]
Closed, thanks very much.
